### ISSUE TITLE
qq加群

### ISSUE THREAD

**Issue by EvoNexusX** [CS-BAOYAN/CS-BAOYAN-2025#46]
现在申请进群的话去哪个群？明年baoyan

**Comment by ZhikangNiu** [comment]
> 现在申请进群的话去哪个群？明年baoyan

如果你是22级本科生，可以申请加入一群，但是需要长期申请（因为waitlist有点多
其他年级加入其他群即可
不要加入多个群

**Comment by EvoNexusX** [comment]
> > 现在申请进群的话去哪个群？明年baoyan
> 
> 如果你是22级本科生，可以申请加入一群，但是需要长期申请（因为waitlist有点多 其他年级加入其他群即可 不要加入多个群

好的谢谢，我是22级本科生，昨天已经申请。

**Comment by Justjustifyjudge** [comment]
> > > 现在申请进群的话去哪个群？明年baoyan
> > 
> > 
> > 如果你是22级本科生，可以申请加入一群，但是需要长期申请（因为waitlist有点多 其他年级加入其他群即可 不要加入多个群
> 
> 好的谢谢，我是22级本科生，昨天已经申请。

其实22级现在加到234群也可以，牛志哥他们消息都会同步的

**Comment by 1023097618** [comment]
申请加了一群但是一直没通过。。。

**Comment by Justjustifyjudge** [comment]
> 申请加了一群但是一直没通过。。。

五六七月人都挺多的不好进，可以试试进其他几个群，群消息和群公告是同步的

**Comment by Oneton429** [comment]
有没有特殊加群通道？22级的，大号被腾讯风控（加群信息全在已过滤里面），小号等级低（真低么，七年的号了）

![Image](https://github.com/user-attachments/assets/3e313f9c-c2e8-47a9-a970-0e6e2af5ab7c)
